In [17]:
import pandas as pd
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm
from statistics import mean
from scipy.stats import t, f

In [18]:
df=pd.read_csv("Case14-2_Safety.csv")
df

    Percent Under 21  Fatal Accidents per 1000
0                 13                     2.962
1                 12                     0.708
2                  8                     0.885
3                 12                     1.652
4                 11                     2.091
5                 17                     2.627
6                 18                     3.830
7                  8                     0.368
8                 13                     1.142
9                  8                     0.645
10                 9                     1.028
11                16                     2.801
12                12                     1.405
13                 9                     1.433
14                10                     0.039
15                 9                     0.338
16                11                     1.849
17                12                     2.246
18                14                     2.855
19                14                     2.352
20                11                     1.294
21                17                     4.100
22                 8                     2.190
23                16                     3.623
24                15                     2.623
25                 9                     0.835
26                 8                     0.820
27                14                     2.890
28                 8                     1.267
29                15                     3.224
30                10                     1.014
31                10                     0.493
32                14                     1.443
33                18                     3.614
34                10                     1.926
35                14                     1.643
36                16                     2.943
37                12                     1.913
38                15                     2.814
39                13                     2.634
40                 9                     0.926
41                17                     3.256

In [24]:
df.describe()

       Percent Under 21  Fatal Accidents per 1000
count         42.000000                 42.000000
mean          12.261905                  1.922405
std            3.131738                  1.070990
min            8.000000                  0.039000
25%            9.250000                  1.017500
50%           12.000000                  1.881000
75%           14.750000                  2.810750
max           18.000000                  4.100000

In [19]:
y=df['Fatal Accidents per 1000']
X=df['Percent Under 21']

In [22]:
model = ols(formula='y ~ X', data=df).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.705
Model:                            OLS   Adj. R-squared:                  0.697
Method:                 Least Squares   F-statistic:                     95.40
Date:                Fri, 09 Mar 2018   Prob (F-statistic):           3.79e-12
Time:                        13:42:05   Log-Likelihood:                -36.364
No. Observations:                  42   AIC:                             76.73
Df Residuals:                      40   BIC:                             80.20
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
Intercept     -1.5974      0.372     -4.298      0.000        -2.349    -0.846
X              0.2871      0.029      9.767      0.000         0.228     0.346
==============================================================================
Omnibus:                        0.328   Durbin-Watson:                   1.725
Prob(Omnibus):                  0.849   Jarque-Bera (JB):                0.113
Skew:                          -0.127   Prob(JB):                        0.945
Kurtosis:                       2.986   Cond. No.                         52.0
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [23]:
anova_results = anova_lm(model)
print(anova_results)

            df     sum_sq    mean_sq          F        PR(>F)
X          1.0  33.134418  33.134418  95.396478  3.793571e-12
Residual  40.0  13.893350   0.347334        NaN           NaN